### ISSUE TITLE
WASMetadataExtractor: update devops prod checklist

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/WASMetadataExtractor#4]
must haves:
- [x] operations checklist written
- [x] mailing list (indicate in checklist and ops concerns?)

at least add TODOs for to prod checklist for
- [x] badges on README for release, and the below,
- [x] travis build that runs tests (if not deploying from jenkins, remove from jenkins)
- [x] coveralls for tests (see dlss-wowza for how to use coveralls w java)

see also #5

**Comment by ndushay** [comment]
addressed by sul-dlss/DevOpsDocs/pull/136
